apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: novapay-runtime-best-practices
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-non-root
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Containers must run as non-root."
        pattern:
          spec:
            containers:
              - securityContext:
                  runAsNonRoot: true
    - name: require-resource-requests-and-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "CPU and memory resource requests and limits are required."
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    memory: "?*"
                    cpu: "?*"
                  limits:
                    memory: "?*"
                    cpu: "?*"
    - name: disallow-latest-image-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Mutable latest image tags are not allowed."
        pattern:
          spec:
            containers:
              - image: "!*:latest"
    - name: require-compliance-labels
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Required labels: app, owner, environment, compliance-scope."
        pattern:
          metadata:
            labels:
              app: "?*"
              owner: "?*"
              environment: "?*"
              compliance-scope: "?*"
