openapi: 3.0.1
info:
  title: NovaPay Lite API
  description: Demo application for testing CI/CD pipelines
  version: v0.0.1
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/health:
    get:
      tags:
        - system-controller
      operationId: getHealth
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/version:
    get:
      tags:
        - system-controller
      operationId: getVersion
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
