apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "novapay-lite.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "novapay-lite.name" . }}
    helm.sh/chart: {{ include "novapay-lite.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "novapay-lite.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "novapay-lite.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ .Values.podLabels.app | quote }}
        owner: {{ .Values.podLabels.owner | quote }}
        environment: {{ .Values.podLabels.environment | quote }}
        compliance-scope: {{ index .Values.podLabels "compliance-scope" | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DEPLOYMENT_COLOR
              value: {{ .Values.deployment.color | quote }}
            - name: DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: DB_NAME
              value: {{ .Values.database.name | quote }}
            - name: DB_USER
              value: {{ .Values.database.user | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret | quote }}
                  key: {{ .Values.database.passwordKey | quote }}
            - name: REDIS_HOST
              value: {{ .Values.redis.host | quote }}
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host | quote }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.existingSecret | quote }}
                  key: {{ .Values.rabbitmq.passwordKey | quote }}
            - name: SIMULATE_FAILURE
              value: {{ .Values.runtime.simulateFailure | quote }}
            - name: SIMULATE_LATENCY_MS
              value: {{ .Values.runtime.simulateLatencyMs | quote }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
